---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kubeflow-ingress-cert
  namespace: istio-system
spec:
  secretName: kubeflow-ingress-cert
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - "$KUBEFLOW_DNS_NAME"